ALTER TABLE users ADD COLUMN display_id VARCHAR(16) NULL UNIQUE;

-- Existing accounts can be backfilled once. New accounts are generated by the backend.
SET @stu := 0;
UPDATE users SET display_id = CONCAT('STU', LPAD((@stu := @stu + 1), 3, '0'))
WHERE role = 'STUDENT' AND display_id IS NULL ORDER BY user_id;

SET @adm := 0;
UPDATE users SET display_id = CONCAT('ADM', LPAD((@adm := @adm + 1), 3, '0'))
WHERE role = 'ADMIN' AND display_id IS NULL ORDER BY user_id;
